// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MicoHoodApi.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MicoHoodApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MicoHoodApi.Entities.PostLike", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("PostId").HasColumnType("uuid");
                b.Property<Guid>("UserId").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.HasIndex("PostId", "UserId").IsUnique();
                b.ToTable("PostLikes");
            });

            modelBuilder.Entity("MicoHoodApi.Entities.Post", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("Content").IsRequired().HasColumnType("text");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<int>("LikesCount").HasColumnType("integer");
                b.Property<string>("Location").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("UserId").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("Posts");
            });

            modelBuilder.Entity("MicoHoodApi.Entities.User", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("text");
                b.Property<string>("Username").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.HasIndex("Username").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("MicoHoodApi.Entities.PostLike", b =>
            {
                b.HasOne("MicoHoodApi.Entities.Post", "Post")
                    .WithMany("Likes").HasForeignKey("PostId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("MicoHoodApi.Entities.User", "User")
                    .WithMany("Likes").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Post");
                b.Navigation("User");
            });

            modelBuilder.Entity("MicoHoodApi.Entities.Post", b =>
            {
                b.HasOne("MicoHoodApi.Entities.User", "User")
                    .WithMany("Posts").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("MicoHoodApi.Entities.Post", b =>
            {
                b.Navigation("Likes");
            });

            modelBuilder.Entity("MicoHoodApi.Entities.User", b =>
            {
                b.Navigation("Likes");
                b.Navigation("Posts");
            });
#pragma warning restore 612, 618
        }
    }
}
